spring.application.name=sevenpoint

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.initialize=false
spring.datasource.url=jdbc:postgresql://localhost:5432/sevenpoint
spring.datasource.username=postgres

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.platform=postgresql
spring.batch.jdbc.schema=classpath:org/springframework/batch/core/schema-@@platform@@.sql


batch.zerodte.cron=0 45 13 * * 1-5
batch.schwab.apikey=PLACEHOLDER
